### ISSUE TITLE
drawing_list_models documentation, description

### ISSUE THREAD

**Issue by Osiel-Gaona** [Zepmanbc/creopyson#18]
Hi,
this description does not match the function

https://creopyson.readthedocs.io/en/latest/creopyson.html#creopyson.connection.Client.drawing_list_models 

**drawing_list_models**(model=None, drawing=None)
Check whether a symbol definition file is loaded into Creo.    _<-------wrong description_

**Comment by Zepmanbc** [comment]
Hi @Osiel-Gaona 
Thanks!
I will replace it in the next release
« List the models contained in a drawing »
