### ISSUE TITLE
Will creopyson have any module for shrinkwrap operation? (eom)

### ISSUE THREAD

**Issue by stekicar** [Zepmanbc/creopyson#38]
* Creo version:
* Creopyson version:
* Creoson version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Zepmanbc** [comment]
creopyson is "just" a Python interface for Creoson.
If Creoson add features, creopyson will. 
You can ask on Creoson's github but I don't think a new feature is needed, you can automate shrinkmap creation with a mapkey and run it with [interface_mapkey](https://creopyson.readthedocs.io/en/latest/creopyson.html#creopyson.connection.Client.interface_mapkey)
you can change values in the mapkey strings if needed

I've made a function with theses arguments: _quality_, _TEMPLATE_DIR_, _TEMPLATE_FILE_
(I didn't test this function, it's a copy/paste with cleaning from my custom, I encourage you to write it by yourself from your mapkey)

```
def shrinkmap(client, quality, directory, filename):
    mapkey = f"~ Command `ProCmdModelSaveAs` ;\
                ~ Select `file_saveas` `type_option` 1 `db_813`;\
                ~ Activate `file_saveas` `OK`;\
                ~ Select `skin` `MethodGroup` 1 `Facets`;\
                ~ Activate `skin` `RmvHolesCheckBtn` 1;\
                ~ Activate `skin` `IgnoreQuiltsCheckBtn` 0;\
                ~ Update `skin` `LevelSpinBox` {quality};\
                ~ Activate `std_warning_modal` `OK`;\
                ~ Select `skin` `FormatGroup` 1 `Part`;\
                ~ Activate `skin` `OKBtn`;\
                ~ Activate `new_file_opts` `psh_browse`;\
                ~ Update `file_open` `opt_EMBED_BROWSER_TB_SAB_LAYOUT` `{directory}`;\
                ~ Activate `file_open` `opt_EMBED_BROWSER_TB_SAB_LAYOUT`;\
                ~ Update `file_open` `Inputname` `{filename}`;\
                ~ Activate `file_open` `Inputname`;\
                ~ Activate `new_file_opts` `chk_create_drawing` 0;\
                ~ Activate `new_file_opts` `psh_ok`;\
                ~ Activate `skin` `CancelBtn`;\
                ~ Command `ProCmdBrowserBtn`  0;"
    client.interface_mapkey(mapkey)
```
