### ISSUE TITLE
view_list_exploded() =>name param must no be defined in request

### ISSUE THREAD

**Issue by Zepmanbc** [Zepmanbc/creopyson#4]
view_list_exploded()

current:
    `data = {'file': 'my_file.prt', 'name': None}`

must be:
    `data = {'file': 'testplante.prt'}`

**Comment by adama2000** [comment]
The name param is not required.  You should be able to leave it off.  Or are you saying that you're not allowed to specify the name param?

**Comment by Zepmanbc** [comment]
I did not tried but I thinks it's more clear with params in the request.
I've open this issue to remember this modification.
It's not a Creoson problem ;)
