### ISSUE TITLE
How to get material list from assembly file?

### ISSUE THREAD

**Issue by yuyaU0507** [Zepmanbc/creopyson#51]
Hi, I'm new to use creopyson.
I'm trying to get a material list from an assembled CAD model (.asm) by using file_list_materials() command, but nothing was returned.
The model certainly includes material information, so I'm wondering how to get the material list from it. 
Is this command perhaps available for only part files?

**Comment by Zepmanbc** [comment]
Hello,
yes, Material is only on parts not on asm
you need to get your parts list from your asm an loop on parts
