### ISSUE TITLE
Any interference check methods?

### ISSUE THREAD

**Issue by yuyaU0507** [Zepmanbc/creopyson#52]
Hi there,
Could I check surface interference in an assembly model with creopyson?
I couldn't find any functions regarding interference check in the creopyson documentation.

**Comment by Zepmanbc** [comment]
Hello,
There is nothing like this in Creoson, maybe you can automate something with mapkeys?
Sorry, I don't use often this feature and never tried to automate it

**Comment by yuyaU0507** [comment]
Hi, 
Okay I'll set a mapkey to check them.
Thanks!
