### ISSUE TITLE
Creating a table on a drawing sheet

### ISSUE THREAD

**Issue by dummifiedme** [Zepmanbc/creopyson#61]
* Creo version: 4.0
* Creopyson version: 
* Creoson version:2.8.1
* Python version: 0.7.4
* Operating System: Windows 10

### Description

Trying to add a table based on some special characteristics on a **drawing sheet.** But I don't see any function to do so.
The same thing is possible with this ribbon and these options.
![image](https://user-images.githubusercontent.com/68785729/206407990-2dc1f8b1-305d-4269-a344-2c67358b70ac.png)

1. Is this the right place to ask such questions?
2. Is there a way to add tables into the drawing sheet?
3. From what I read online, there is no way to edit an existing table (till 2020). Is there a development on that line?

**Comment by Zepmanbc** [comment]
Hi, sorry I don't know and I don't think there should be something like thaht in JLink if you say it only exists until 2020
