### ISSUE TITLE
creopyson.layer.delete

### ISSUE THREAD

**Issue by stekicar** [Zepmanbc/creopyson#68]
* Creo version: 5.0.6
* Creopyson version: 0.7.3
* Creoson version: 2.8.1
* Python version: 3.10
* Operating System: Win10

I am trying to remove all layers from part/assembly using following code:
```
for component in component_list:
    creopyson.layer.delete(srv, name=None, file_=component)
```
But I do not get any layer removed. Documentation show "Layer name (wildcards allowed: True). Defaults: All layers will be deleted." I think that None means "all will be removed"?

Here is the error:
RuntimeError: Invalid JSON input: {"sessionId": "4726948925695228620", "command": "layer", "function": "delete", "data": {"name": null, "file": "20-111_joining_plate.prt"}}

Under "name" it says null which is not None value. What should I put for "name" so all layers are deleted?

**Comment by Zepmanbc** [comment]
Hello
Release V0.7.6 should correct this
