### ISSUE TITLE
Cannot set the location of a note

### ISSUE THREAD

**Issue by jordifas** [Zepmanbc/creopyson#69]
* Creo version: 6
* Creopyson version: 0.7.6
* Creoson version: 2.8.2
* Python version: 3.11
* Operating System: W10

### Description
I cannot set the location of a note:

### What I Did

creopyson.note.set_(c,nom_nou, value=tex_nota, location=ubicacio)  
TypeError: set_() got an unexpected keyword argument 'location'

**Comment by Zepmanbc** [comment]
Hi,

I don't understand this error, there is the `location` argument
You should use `c.note_set(nom_nou, value=tex_nota, location=ubicacio)` notation
does `ubicacio` is a dict like `{'x':50,'y':50}` ?

**Comment by jordifas** [comment]
Sorry, I used version 0.7.4. I updated and it is solved.
