### ISSUE TITLE
Mapkey not working

### ISSUE THREAD

**Issue by jordifas** [Zepmanbc/creopyson#70]
* Creo version: 6.0.6
* Creopyson version: 0.7.6
* Creoson version: 2.8.2
* Python version: 3.11
* Operating System: W10

### Description
I try to run a mapkey but it did nothing. If I run it manually in Creo it works perfectly. I removed the "mapkey(continued)".

### What I Did
import creopyson

c = creopyson.Client()
c = creopyson.Client()
c.connect()
c.interface_mapkey("FA4")

Then the mapkey is 

mapkey FA4 @MAPKEY_NAMEFormato A4;@MAPKEY_LABELFormato A4;\
~ Activate `main_dlg_cur` `page_Layout_control_btn` 0;\
~ Command `ProCmdDwgPageSetup` ;~ Arm `pagesetup` `TblFormats` 2 `0` `fmt`;\
~ Select `pagesetup` `TblFormats` 2 `0` `fmt`;\
~ Open `pagesetup` `TblFormats_INPUT`;~ Close `pagesetup` `TblFormats_INPUT`;\
~ Select `pagesetup` `TblFormats_INPUT` 1 `Browse...`;\
~ Trail `UI Desktop` `UI Desktop` `DLG_PREVIEW_POST` `file_open`;\
~ Activate `file_open` `workspace_pb`;\
~ Select `file_open` `Ph_list.Filelist` 1 `a4-elebia.frm`;\
~ Activate `file_open` `Ph_list.Filelist` 1 `a4-elebia.frm`;\
~ Activate `pagesetup` `OK`;~ Activate `keep_format_tables` `RemoveAll`;\
~ Activate `0_std_confirm` `OK`;

**Comment by Zepmanbc** [comment]
Hello
You cannot call the mapkey with it's name, you must put the mapkey definition in the parameter of `interface_mapkey()` function

something like this:
```
mapkey_FA4 = "~ Activate main_dlg_cur page_Layout_control_btn 0;\
~ Command ProCmdDwgPageSetup ;~ Arm pagesetup TblFormats 2 0 fmt;\
~ Select pagesetup TblFormats 2 0 fmt;\
~ Open pagesetup TblFormats_INPUT;~ Close pagesetup TblFormats_INPUT;\
~ Select pagesetup TblFormats_INPUT 1 Browse...;\
~ Trail UI Desktop UI Desktop DLG_PREVIEW_POST file_open;\
~ Activate file_open workspace_pb;\
~ Select file_open Ph_list.Filelist 1 a4-elebia.frm;\
~ Activate file_open Ph_list.Filelist 1 a4-elebia.frm;\
~ Activate pagesetup OK;~ Activate keep_format_tables RemoveAll;\
~ Activate 0_std_confirm OK;"

c.interface_mapkey(mapkey_FA4)
```
