### ISSUE TITLE
File types of import_file

### ISSUE THREAD

**Issue by IsmaG412** [Zepmanbc/creopyson#73]
* Creo version: 8.0.2
* Creopyson version: 0.7.6
* Creoson version: 2.8.2
* Python version: 3.11.3
* Operating System: windows 10 pro

### Description

I would like to know if it is possible to implement the import_file function of the interface module to import file types other than the standard ones, such as a .sldprt file

**Comment by Zepmanbc** [comment]
This is a Creoson's feature, valid values are IGES, NEUTRAL, PV, STEP, if you send SLDPRT it will raise an error.
Probably a Jlink restriction? You should ask Creoson guys

You can probably use a mapkey to import your sldprt file (nether tried)
