### ISSUE TITLE
How to do "save as" with creopyson?

### ISSUE THREAD

**Issue by yuyaU0507** [Zepmanbc/creopyson#79]
* Creo version: 4.0
* Creopyson version: 0.7.6
* Creoson version: 2.8.1
* Python version: 3.11
* Operating System: Win10

### Description

I would like to save a CAD file with different name. I found "file_save" command but the function seems to overwrite the file.
Do you know any other functions that save files with different names?
Should I use mapkey instead?

Thanks!

**Comment by Zepmanbc** [comment]
Hi,
Yes you should use mapkey
Save as should be complex for ASM, this should be the reason there is no build in save as function

**Comment by adama2000** [comment]
I believe that file:backup might work.  Not at my computer right now or I'd
check.

**Comment by yuyaU0507** [comment]
Hi,
I tried "file_backup" to save a file to other directory then it works.
I'll rename the file with commands. 
Thanks
