### ISSUE TITLE
How to save each family table instance of a generic model as individual model files

### ISSUE THREAD

**Issue by Pascal-m** [Zepmanbc/creopyson#81]
Creopyson version: Version:0.7.6
Creoson version: Version 2.8.2
Python version: Version:3.9.1
Operating System: windows 10 x64

### Description
Is it possible to save each family table instance of a generic model as individual model files?

### What I Need

I think if there was the "save a copy" function I could achieve this

Thk :)

**Comment by Zepmanbc** [comment]
Hi Pascal,
You should loop on each instance, open and run a mapkey to backup
creopyson implements only creoson features

**Comment by Pascal-m** [comment]
Hi Zepmanbc,
Ok thk
