### ISSUE TITLE
"feature_suppress" for parts in subassembly

### ISSUE THREAD

**Issue by yuyaU0507** [Zepmanbc/creopyson#83]
* Creo version: 4.0
* Creopyson version: 0.7.6
* Creoson version: 2.8.1
* Python version: 3.11
* Operating System: Win10x64

### Description

Is it possible to suppress features (parts) included in a subassembly by using "feature_suppress"?

### What I Did

Model configuration:

model.asm
　┣subasm.asm
　┃　┣subasmmodel.prt
　┃　┗subasmmodel2.prt
　┣model2.prt
　┗model3.prt

I tried feature_suppress(name="subasmmodel.prt") to suppress but the part remained active.
Suppressing other part (for model2.prt or model3.prt) successfully worked.

Should I add variables to the command?

Thanks!

**Comment by Zepmanbc** [comment]
Hi, the feature does not belong to the opened model so you cannot supress it like in GUI
You must open the part/asm  in which the feature/part is referenced

You can open your subasm without show it, suppress what you want, regenerate, close. I'ts quick so you can think it would have been done it without open subasm.asm

**Comment by yuyaU0507** [comment]
Thank you for your suggestion!
I tried commands below but models were not seemed to be suppressed.

file_open(file_="subasm.asm", display=False)
feature_suppress(name="subasmmodel.prt")
file_regenetrate(file_="subasm.asm")
file_close_window(file_="subasm.asm")

Would you know they are correct?

**Comment by Zepmanbc** [comment]
you probably need to regenerate model.asm too

**Comment by Zepmanbc** [comment]
it's been a long time I did not look at creopyson, sorry
if that does not work, you should have to do this with mapkeys
 * select the part you want (but you will still need to open subasm and look after subasmmodel with the mapkey)
 * then a mapkey that suppress the selected item in tree

**Comment by yuyaU0507** [comment]
Finally, I found these commands below works:

file_open(file_="subasm.asm", new_window=True, display=True)  
feature_suppress(name="subasmmodel.prt")
file_close_window(file_="subasm.asm")
file_regenetrate(file_="subasm.asm")
file_open(file_="model.asm", new_window=False, display=True)

Thank you for your advices.
