### ISSUE TITLE
STEP interface_export_file

### ISSUE THREAD

**Issue by yuyaU0507** [Zepmanbc/creopyson#85]
* Creo version: 4.0
* Creopyson version: 0.7.6
* Creoson version: 2.8.0
* Python version: 3.11
* Operating System: Win10

### Description
Hi,

I use interface_export_file command to export a file in STEP format. But I wonder how to specify the format (such as ap203 and ap242). 
Could you tell me what format is specified as default and how to change it?

Thank you!

**Comment by Zepmanbc** [comment]
Hi you can't specify this with Creoson, maybe you can do a mapkey
