### ISSUE TITLE
bom_get_paths acquired SUPPRESSED feature info

### ISSUE THREAD

**Issue by yuyaU0507** [Zepmanbc/creopyson#88]
* Creo version: 4.0
* Creopyson version: 0.7.7
* Creoson version: 0.2.8
* Python version: 3.11.4
* Operating System: win10

### Description

Hi there,
I'd like to obtain component info including in an assembly file.
I tried bom_get_paths() to do this, and found a returned text containing info on some suppressed components.
These components are not contained in a bom output from the Creo's default function.
Thus I wonder how and why this info was obtained from the function because some suppressed components were listed in the bom and the remaining were not.
The function will still exclude any components with a status of INACTIVE or UNREGENERATED as described in the Creopyson Documentation. Does it exclude suppressed components?

**Comment by Zepmanbc** [comment]
Sorry I can't give you a good answer, you could ask your question on [Creoson's page](https://github.com/SimplifiedLogic/creoson/issues)
